#!/usr/bin/env php

<?php

/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 22/08/2017
 * Time: 1:10 PM
 */

use Symfony\Component\Console\Application;
use phplab\commands\services\Config;

use phplab\commands\db\Db;

use phplab\commands\lnmp\Lnmp;
use phplab\commands\url\Url;

require 'vendor/autoload.php';

$config = Config::getValue();
$app = new Application($config['info']['app'], $config['info']['version']);

$app->add(new Db());

$app->add(new Lnmp());
$app->add(new Url());

try {
    $app->run();
} catch (Exception $e)
{
    printf($e->getMessage());
    return;
}
