#!/usr/bin/env php

<?php

/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 22/08/2017
 * Time: 1:10 PM
 */

use app\lnmp\Lnmp;
use app\services\Config;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$config = Config::getValue();
$app = new Application($config['info']['app'], $config['info']['version']);

$app->add(new Lnmp());

$app->run();